### ISSUE TITLE
terraform init fails with reference to undeclared output value jx_requirements

### ISSUE THREAD

**Issue by arpad9** [jenkins-x/terraform-aws-eks-jx#100]
### Summary 
Failure during `terraform init` wrt undeclared jx_requirements value from the eks-jx module.

### Steps to reproduce the behavior

Using the documented main.tf, run `terraform init`

### Expected behavior

Cluster creates

### Actual behavior

Error:
```
Error: Reference to undeclared output value
  on main.tf line 17, in output "jx_requirements":
  17:    value = module.eks-jx.jx_requirements

An output value with the name "jx_requirements" has not been declared in
module.eks-jx.
```

### Terraform version

The output of `terraform version` is:

```
Terraform v0.12.28
+ provider.aws v2.68.0
+ provider.kubernetes v1.11.1
+ provider.local v1.4.0
+ provider.null v2.1.2
+ provider.random v2.2.1
+ provider.template v2.1.2

```

### Module version

`1.1.0`

### Operating system

Ubuntu 20.04

### Solution

Seems that the variable `module.eks-jx.jx_requirements` is no longer exposed by the eks-jx module.
The solution was to remove the clause:
```
output "jx_requirements" {
   value = module.eks-jx.jx_requirements
}
```
The `terraform init` still creates the jx_requirements output without this clause.
Maybe this is deprecated.

I'd be happy to do a PR if this is a documentation change.

**Comment by ankitm123** [comment]
@arpad9 seems like a duplicate of #101. May be close this?

**Comment by arpad9** [comment]
@ankitm123 I wasn't sure what the direction was.  Is jx_requirements no longer available for use?  Then the two issues could be merged simply by removing the output completely.  Problem solved.  Can certainly be handled in a single PR.

**Comment by arpad9** [comment]
Closing in favor of a single issue: #101
