### ISSUE TITLE
documentation: parens are off for main.tf in one place

### ISSUE THREAD

**Issue by arpad9** [jenkins-x/terraform-aws-eks-jx#101]
### Summary 

The README shows contradictory parentheses placement for main.tf. 

The following section shows the output inside the `module` scope.  That doesn't work.
The preceding section has the output outside of the module scope.  That does work.

```
module "eks-jx" {
  source  = "jenkins-x/eks-jx/aws"

  output "jx_requirements" {
    value = module.eks-jx.jx_requirements
  }

  vault_user="<your_vault_iam_username>"
}
```

### Steps to reproduce the behavior

Figure which one is right.

### Expected behavior

Documentation to be consistent.

### Actual behavior

The above form of the `main.tf` produces an error:
```
Error: Unsupported block type

  on main.tf line 19, in module "eks-jx":
  19:   output "vault_user_id" {

Blocks of type "output" are not expected here.
```

### Terraform version

The output of `terraform version` is:

```
Terraform v0.12.28
+ provider.aws v2.68.0
+ provider.kubernetes v1.11.1
+ provider.local v1.4.0
+ provider.null v2.1.2
+ provider.random v2.2.1
+ provider.template v2.1.2
```

### Module version

`1.1.0`

### Operating system

Ubuntu 20.04

### Solution

Update docs.  Be happy to do it, if that's what's required.

**Comment by ankitm123** [comment]
@arpad9 Good catch :+1: . A PR would be really appreciated :100:

**Comment by arpad9** [comment]
Combined with issues #99 and #100
