### ISSUE TITLE
node_group_disk_size does not affect disk size

### ISSUE THREAD

**Issue by ajp-lqx** [jenkins-x/terraform-aws-eks-jx#105]
### Summary 

I tried setting `node_group_disk_size = "200"` (the docs specify this is a string and not a number) but the node group created had 50Gi disks.

### Steps to reproduce the behavior

Set `node_group_disk_size = "200"` in `main.tf` and run `terraform apply`

### Expected behavior

The created node group has a disk size of 200Gi.

### Actual behavior

The created node group has a disk size of 50Gi (the default).

### Terraform version

The output of `terraform version` is:

```
$ terraform version
Terraform v0.12.28
+ provider.aws v2.69.0
+ provider.kubernetes v1.11.1
+ provider.local v1.4.0
+ provider.null v2.1.2
+ provider.random v2.3.0
+ provider.template v2.1.2
```

### Operating system

Ubuntu 19.04

**Comment by ankitm123** [comment]
@ajp-lqx I see the issue, the variable is not passed to the module as an input. I will have a fix by tonight.

/assign @ankitm123

**Comment by ajp-lqx** [comment]
Awesome, no rush it's easy enough to fix manually, thank you for your help :)
