### ISSUE TITLE
PRs being merged without releases

### ISSUE THREAD

**Issue by patrickleet** [jenkins-x/terraform-aws-eks-jx#114]
### Summary 

Releases don't happen automatically - the last couple PRs that have been merged are not available in any releases, and the docs therefore reference things that are unavailable.

**Comment by ankitm123** [comment]
I think only people with access to cloudbees servers can release atm, but this is the process: https://github.com/jenkins-x/terraform-aws-eks-jx#releasing (It's not like the jx repo, where every PR merged to master creates a new tag, and I think there was an issue in the jx repo about not tagging every commit to master).

**Comment by patrickleet** [comment]
looks like at least #104 and #106 have been merged but not released

**Comment by ankitm123** [comment]
As discussed, @patrickleet, just using the source without version will fetch the latest and greatest changes from master.
```
module "eks-jx" {
  source = "jenkins-x/eks-jx/aws"
}
```
Closing this.

/close

**Comment by patrickleet** [comment]
@ankitm123 

That doesn't work as it pulls from Terraform registry.

You can pull from Github, but the format is:

```
module "eks-jx" {
  source = "github.com/jenkins-x/terraform-aws-eks-jx"
}
```

**Comment by patrickleet** [comment]
This has not been resolved

**Comment by ankitm123** [comment]
I guess, we wait for hardy to release it for now.

**Comment by ankitm123** [comment]
New tag was created and pushed, Closing this.

/close
