### ISSUE TITLE
terraform destroy fails on igw and s3 bucket

### ISSUE THREAD

**Issue by arpad9** [jenkins-x/terraform-aws-eks-jx#122]
### Summary 
After a long timeout on attempting to delete the gateway, the destroy fails but the state bucket is gone.

### Steps to reproduce the behavior
`terraform destroy`

### Expected behavior
Destruction

### Actual behavior
No destruction.  Error.
```
module.eks-jx.module.cluster.module.vpc.aws_internet_gateway.this[0]: Still destroying... [id=igw-09c435482377cadb8, 14m50s elapsed]
Failed to save state: failed to upload state: NoSuchBucket: The specified bucket does not exist
        status code: 404, request id: <redacted>, host id: <redacted>
                                                  
Error: Failed to persist state to backend.                                                                
                                                                                                          
The error shown above has prevented Terraform from writing the updated state
to the configured backend. To allow for recovery, the state has been written
to the file "errored.tfstate" in the current working directory.
                                                                                                          
Running "terraform apply" again at this point will create a forked state,
making it harder to recover.                     

To retry writing this state, use the following command:           
    terraform state push errored.tfstate      
```
Bucket is gone.

Workaround: I recreated the bucket and pushed the errored.tfstate, however, the IGW delete still hangs.

### Terraform version

The output of `terraform version` is:

```
Terraform v0.12.28
```

### Module version

1.4.0

### Operating system

Ubuntu 20.04

**Comment by arpad9** [comment]
Deleted autoscaling group for workers, manually.
Trying to detach the igw manually resulted in an error that it still has mapped public IP's.
Deleted load balancer, subnets, interfaces, security groups, by hand; as it allowed me based on dependencies.

Now terraform destroy is completely borked.

```
Error: Error in function call

  on .terraform/modules/eks-jx.cluster.vpc/terraform-aws-vpc-2.39.0/main.tf line 934, in resource "aws_route_table_association" "private":
 934:   subnet_id = element(aws_subnet.private.*.id, count.index)
    |----------------
    | aws_subnet.private is empty tuple
    | count.index is 0

Call to function "element" failed: cannot use element function with an empty
list.


Error: Error in function call

  on .terraform/modules/eks-jx.cluster.vpc/terraform-aws-vpc-2.39.0/main.tf line 934, in resource "aws_route_table_association" "private":
 934:   subnet_id = element(aws_subnet.private.*.id, count.index)
    |----------------
    | aws_subnet.private is empty tuple
    | count.index is 1

Call to function "element" failed: cannot use element function with an empty
list.


Error: Error in function call

  on .terraform/modules/eks-jx.cluster.vpc/terraform-aws-vpc-2.39.0/main.tf line 934, in resource "aws_route_table_association" "private":
 934:   subnet_id = element(aws_subnet.private.*.id, count.index)
    |----------------
    | aws_subnet.private is empty tuple
    | count.index is 2

Call to function "element" failed: cannot use element function with an empty
list.
```

**Comment by arpad9** [comment]
This has been my experience with every attempted `terraform destroy`

**Comment by ankitm123** [comment]
The detaching of igw is most likely an issue with the aws vpc package we use (I have had the same issues), let me check of there is a way around it. I will play around a bit this weekend, and atleast document this. 
This occurs cuz of dependency errors, a good explanation is here: https://aws.amazon.com/premiumsupport/knowledge-center/troubleshoot-dependency-error-delete-vpc/
My guess is `depends_on` is missing in the aws vpc for some resources (or we are not using some arguments), so terraform cannot explicitly infer which resource depends on which. We may need a depends on between the nodegroup/worker nodes created by the eks module, and the vpc resources created by the vpc module.

/assign @ankitm123

**Comment by arpad9** [comment]
Update:
Destroying again.
- It does remote the s3 bucket too early and fails on that.  Solution: recreate the bucket and push the errorred.tfstate
- I only deleted the ASG and ELB by hand and then re-ran destroy and it worked
