### ISSUE TITLE
s3 buckets should include options to create with kms encryption

### ISSUE THREAD

**Issue by arpad9** [jenkins-x/terraform-aws-eks-jx#123]
### Summary 
Currently, the AWS S3 buckets for logs, reports and repository are created with no encryption.

### Steps to reproduce the behavior
Run jx boot

### Expected behavior
Provide an option to specify a kms id and create the buckets with encryption.

### Actual behavior
Buckets are created with no encryption.

### Terraform version

The output of `terraform version` is:

```
Terraform v0.12.28
```

### Module version

1.4.0

### Operating system
Ubuntu 20.04

**Comment by ankitm123** [comment]
@arpad9 Quick question: All you want is to specify the id of an existing kms key, right? I assume you don't want the module to create a kms key, right?

This is what I am thinking:
* Expose variables `use_kms` and `s3_kms_key_id`
* If `use_kms` is set to false (the default), then use AES-256 to encrypt bucket
* If `use_kms` is set to true, then look at `s3_kms_key_id` variable
* If `s3_kms_key_id` is empty, then use the aws kms s3 master key, else use the user supplied. 

Sounds good?

**Comment by arpad9** [comment]
@ankitm123 Yup, that's exactly what I was thinking.  Thanks!
