### ISSUE TITLE
starting fresh, region error updating kubeconfig

### ISSUE THREAD

**Issue by arpad9** [jenkins-x/terraform-aws-eks-jx#125]
### Summary 
with the env var `AWS_REGION=us-east-1`
and main.tf including:
`region = "us-east-1"`
in the eks-jx module section

### Steps to reproduce the behavior

On a fresh init with all AWS artifacts removed.
`terraform apply`

### Expected behavior
New cluster.

### Actual behavior
```
Error: Error running command 'aws eks update-kubeconfig --name jenkins': exit status 255. Output: You must specify a region. You can also configure your region by running "aws configure".
```
### Terraform version

The output of `terraform version` is:

```
Terraform v0.12.28
+ provider.aws v2.70.0
+ provider.kubernetes v1.11.1
+ provider.local v1.4.0
+ provider.null v2.1.2
+ provider.random v2.3.0
+ provider.template v2.1.2

Your version of Terraform is out of date! The latest version
is 0.13.0. You can update by downloading from https://www.terraform.io/downloads.html

```

### Module version
1.4.0

### Operating system
Ubuntu 20.04

**Comment by arpad9** [comment]
Workaround:
set `AWS_PROFILE`
ran `aws eks update-kubeconfig --name jenkins`
`terraform init`
`terraform apply`

**Comment by ankitm123** [comment]
I always use AWS_PROFILE, should be documented.

**Comment by arpad9** [comment]
Shouldn't everything fall back to the default profile if not set?

**Comment by arpad9** [comment]
Or at least, shouldn't there be a check for this before the cluster starts being created?

**Comment by ankitm123** [comment]
In my case, I use the test profile (linked to the testing account), so I have to explicitly set the profile, I tried doing it in the module, but it's been flaky. I have not been able to get it to work.

> Shouldn't everything fall back to the default profile if not set?

Yes

Exact same issue with region not being passed by terraform. Worth an investigation imo.

**Comment by ankitm123** [comment]
This was fixed by passing region to `aws eks update-config`, closing this issue.
