### ISSUE TITLE
upgrading to 1.5.0 - The argument "key_name" is required, but no definition was found

### ISSUE THREAD

**Issue by patrickleet** [jenkins-x/terraform-aws-eks-jx#126]
### Summary 

Error `The argument "key_name" is required, but no definition was found.` when upgrading from `1.4.0` to `1.5.0`.

The docs seem to suggest it is optional.

### Steps to reproduce the behavior

Change version from `1.4.0` to `1.5.0` then plan:

```
> terraform plan -out=jxmodule.tfplan

Error: Missing required argument

  on jx.tf line 1, in module "eks-jx":
   1: module "eks-jx" {

The argument "key_name" is required, but no definition was found.
```

### Expected behavior

I don't need to set an optional argument.

### Actual behavior

Error

### Terraform version

The output of `terraform version` is:

```
Terraform v0.12.29
+ provider.aws v2.68.0
+ provider.kubernetes v1.11.1
+ provider.local v1.4.0
+ provider.null v2.1.2
+ provider.random v2.3.0
+ provider.template v2.1.2

Your version of Terraform is out of date! The latest version
is 0.13.0. You can update by downloading from https://www.terraform.io/downloads.html
```

### Module version

When planning 1.4.0 -> 1.5.0

### Operating system

Mac

**Comment by patrickleet** [comment]
https://github.com/jenkins-x/terraform-aws-eks-jx/commit/6e085c2#r41477692

**Comment by arpad9** [comment]
I looked at the above commit but had no success with `enable_key_name = false`
Instead, my workaround was just to add `key_name = ""`
