### ISSUE TITLE
Conditional creation

### ISSUE THREAD

**Issue by naliwajek** [jenkins-x/terraform-aws-eks-jx#186]
### Summary 

Hi.

What do you think about adding conditional creation?

It helps when you have many workspaces using same code and you just want to pass configuration variables to enable or disable parts of your environment.

[See example here.](https://registry.terraform.io/modules/terraform-aws-modules/eks/aws/latest#conditional-creation)

Would it be OK with you to add it to this repo? I can try to make a PR if yes 😄 

(Or perhaps I can't read and it's already implemented under some argument 🙈 )

Cheers.

**Comment by ankitm123** [comment]
@naliwajek This is a valid request, and there is another issue abt it: #67, which I am working on currently. I should have it done soonish.

**Comment by pparth** [comment]
generally, we should have the ability to parameterize these Terraform scripts fully. E.g. in our case, we already have an EKS cluster, an ECR, a Vault installation and others.

**Comment by ankitm123** [comment]
> generally, we should have the ability to parameterize these Terraform scripts fully. E.g. in our case, we already have an EKS cluster, an ECR, a Vault installation and others.

That is what I am working towards, as it's a requirement.
