### ISSUE TITLE
Error during release pippeline performing jx project quickstart using react-quickstart

### ISSUE THREAD

**Issue by xcesiv** [jenkins-x/terraform-aws-eks-jx#191]
### Summary 
Started from scratch using [EKS Get Started](https://jenkins-x.io/docs/v3/getting-started/eks/). Installation goes great. Performing `jx project` selecting `react-quickstart` results in permission error:

```E1102 14:30:34.538559      14 aws_credentials.go:77] while getting AWS credentials WebIdentityErr: failed to retrieve credentials caused by: AccessDenied: Not authorized to perform sts:AssumeRoleWithWebIdentity```

It looks like there is a problem with the naming of service account for tekon bot.
in file:
` eks.amazonaws.com/role-arn: arn:aws:iam::<account>:role/<cluster>-jx-tekton-bot`

in aws:
`<account>:role/<cluster>-tekton-bot`

Also appears `DOCKER_REGISTRY_ORG` isn incorrect.

set to gitorg name, should be aws account.

### Steps to reproduce the behavior
Install jx3 using getting started page.
`jx ns jx`
`jx project`
 Select quickstart
Select `react-quickstart`
Select `javascript`

### Expected behavior
Release pipeline should complete and make repository

### Actual behavior
release pipeline fails due to permissions issue for tekton bot.

### Terraform version

The output of `terraform version` is:

```
Terraform v0.13.5
```

### Module version

latest

### Operating system

mac os Catalina v10.15.7

**Comment by xcesiv** [comment]
Creating the repository in ECR manually will resolve it for pr pipeline

**Comment by ankitm123** [comment]
@xcesiv this can be closed, since the version stream was updated. if not, let me know.

**Comment by ankitm123** [comment]
Closing this @xcesiv, re-open another issue, if it's not fixed yet.
