### ISSUE TITLE
Remove the need for specifying an additional IAM user for Vault

### ISSUE THREAD

**Issue by hferentschik** [jenkins-x/terraform-aws-eks-jx#20]
Currently, you need to create an additional IAM user just for the Vault setup and you also need to export the credentials for this user in environment variables prior to running `jx boot`. This is not clear in the documentation and easy to get wrong leading to failing Jenkins X installs.

Initially, this was required due to some issues with Vault which got resolved upstream. Now that a new Vault version is available we can remove this workaround.

On the Terraform side we will need to set up proper IAM Roles for Service Accounts for Vault. 
However, there are also changes required in `jx` itself. We need make sure that the Vault Operator uses the right version of Vault and the the current `jx boot` code will also make use of the new way to configure the Vault setup (this is to ensure that at least for now one can still use `jx create cluster` with `jx boot` creating all resources).

**Comment by hferentschik** [comment]
This docs document will need to be updated as well together with the `jx` changes - https://jenkins-x.io/docs/getting-started/setup/boot/clouds/amazon/

**Comment by hferentschik** [comment]
See also https://github.com/jenkins-x/jx/issues/6997

**Comment by deanesmith** [comment]
Hashicorp PR merge did not make it in to latest release

**Comment by mrmarcsmith** [comment]
Any Chance the Hashicorp PR has been merged since this? I would love to use an IAM Role instead of a user as well.
