### ISSUE TITLE
JX3 setup failing. Kubernetes cluster unreachable: invalid configuration. 

### ISSUE THREAD

**Issue by serhiy-krupka-vitech** [jenkins-x/terraform-aws-eks-jx#233]
### Summary 
JX3 setup failed on AWS

### Steps to reproduce the behavior
1. generate repo from https://github.com/jx3-gitops-repositories/jx3-terraform-eks/generate (commit https://github.com/jenkins-x/terraform-aws-eks-jx/tree/af1182fc3d07881af6a96a2335255ef7b0dce7f6)

2. generate repo from  https://github.com/jx3-gitops-repositories/jx3-eks-vault/generate
3. configure terraform variables 
4. execute: `terraform apply`

### Expected behavior
Boot job stated without errors.

### Actual behavior

```
module.eks-jx.module.cluster.module.iam_assumable_role_cluster_autoscaler.aws_iam_role_policy_attachment.custom[0]: Creating...
module.eks-jx.module.cluster.module.iam_assumable_role_pipeline_visualizer.aws_iam_role_policy_attachment.custom[0]: Creating...
module.eks-jx.module.cluster.module.iam_assumable_role_external_dns.aws_iam_role_policy_attachment.custom[0]: Creation complete after 1s [id=jx-test-external-dns-20210121104622556100000019]
module.eks-jx.module.cluster.module.iam_assumable_role_controllerbuild.aws_iam_role_policy_attachment.custom[0]: Creation complete after 1s [id=jx-test-build-ctrl-2021012110462263690000001a]
module.eks-jx.module.cluster.module.iam_assumable_role_cm_cainjector.aws_iam_role_policy_attachment.custom[0]: Creation complete after 1s [id=jx-test-cert-manager-cert-manager-cainjector-2021012110462269650000001b]
module.eks-jx.module.cluster.module.iam_assumable_role_cluster_autoscaler.aws_iam_role_policy_attachment.custom[0]: Creation complete after 1s [id=jx-test-cluster-autoscaler-cluster-autoscaler-2021012110462283150000001c]
module.eks-jx.module.cluster.module.iam_assumable_role_pipeline_visualizer.aws_iam_role_policy_attachment.custom[0]: Creation complete after 1s [id=jx-test-jx-pipelines-visualizer-2021012110462286320000001d]
module.eks-jx.module.cluster.module.iam_assumable_role_tekton_bot.aws_iam_role_policy_attachment.custom[0]: Creation complete after 1s [id=jx-test-tekton-bot-2021012110462288510000001f]
module.eks-jx.module.cluster.module.iam_assumable_role_cert_manager.aws_iam_role_policy_attachment.custom[0]: Creation complete after 1s [id=jx-test-cert-manager-cert-manager-2021012110462288200000001e]
module.eks-jx.module.cluster.null_resource.kubeconfig (local-exec): Updated context arn:aws:eks:eu-central-1:xxx:cluster/jx-test in /Users/serhiykrupka/.kube/config
module.eks-jx.module.cluster.null_resource.kubeconfig: Creation complete after 1s [id=5757698152048227794]
module.eks-jx.module.cluster.helm_release.jx-git-operator[0]: Creating...

Error: Kubernetes cluster unreachable: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable



Error: Kubernetes cluster unreachable: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
```

### Terraform version

```
v0.13.3
```

### Operating system

MacOS 11.1

**Comment by nnsense** [comment]
Same here
- terraform version `v0.14.5`
- OS `CentOS Linux release 7.9.2009 (Core)`
- helm `version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"clean", GoVersion:"go1.14.13"}`

**Comment by nnsense** [comment]
I did some testing and apparently if I set to `false` the option `install_kuberhealthy` I get the error only one time:
```
Error: Kubernetes cluster unreachable: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
```
If I set it back, I get 2 errors like that, as you can see in both mine and OP log, so (maybe) that option is related.

Hope it helps.

**Comment by jstrachan** [comment]
we fixed the kuberhealthy issue here: https://github.com/jenkins-x/terraform-jx-health/commit/9d99da326fcb87d4c9b0fa973f2ac13e83aa12d1 it was caused by a new kuberhealthy chart breaking

**Comment by jstrachan** [comment]
I wonder if you could remove your `.terraform` folder and rerun `terraform plan && terraform apply`?

**Comment by nnsense** [comment]
Sure, currently destroying, will start over and update, thanks! :)

**Comment by Frejl** [comment]
same issue for me.

**Comment by nnsense** [comment]
Update: Unfortunately I'm getting the same behaviour starting with a new deployment (no `.terraform`)

**Comment by patrickleet** [comment]
https://kubernetes.slack.com/archives/C9MBGQJRH/p1611693802377700?thread_ts=1611679357.370700&channel=C9MBGQJRH&message_ts=1611693802.377700

**Comment by ankitm123** [comment]
/assign
I have been doing what @patrickleet suggested in the slack message. Let me check why this is breaking, will report back.

**Comment by dephee** [comment]
i had the same problem. I fixed that by adding helm provider config
```
provider "helm" {
  kubernetes {
      config_path = "./kubeconfig_jenkins"
  }
}
```

it will fail on first call, but it will success on second call, after kubeconfig_jenkins is created

**Comment by ankitm123** [comment]
> it will fail on first call, but it will success on second call, after kubeconfig_jenkins is created

So the reason this happened was because, the helm provider uses outdated kube config on the first apply, then when you apply the second time, it has access to the correct credentials and applies successfully. 

@dephee  Would be nice to give my branch a try, and see if the error goes away - wont need the provider helm block anymore in the `main.tf` file.
