### ISSUE TITLE
no Jenkins UI is shown after successful `jx boot --requirements jx-requirements.yml`

### ISSUE THREAD

**Issue by sarveshhh** [jenkins-x/terraform-aws-eks-jx#236]
### Summary 
no Jenkins UI is shown after successful `jx boot --requirements jx-requirements.yml`

### Steps to reproduce the behavior
Followed steps from https://jenkins-x.io/docs/

### Expected behavior
Jenkins URL should come up. Not sure, if it is expected behaviour.

### Actual behavior
I don't see Jenkins UI url. Not sure if that is expected behaviour. On running `jx get urls` -

```
hook                                  http://hook-jx.1.2.3.4.nip.io
jenkins-x-chartmuseum  http://chartmuseum.jx.1.2.3.4.nip.io
jx-vault-tf-jx-comic-o      http://vault-jx.1.2.3.4.nip.io
nexus                                 http://nexus-jx.1.2.3.4.nip.io
```
But there is no Jenkins URL shown.

### Terraform version
0.12.24

The output of `terraform version` is:

```
Terraform v0.12.24
```

### Module version

1.8.0 

### Operating system

Mac OS CATALINA

**Comment by sarveshhh** [comment]
Tagging some key members for valuable inputs. @jstrachan

**Comment by ankitm123** [comment]
@sarveshhh You should use jenkinsx v3, it's the preferred way to go forward: https://jenkins-x.io/v3/about/

**Comment by sarveshhh** [comment]
Ok, Thanks @ankitm123 ; I will deploy JX-v3 and see if I face same issue.

**Comment by sarveshhh** [comment]
I was able to deploy it as per my requirements.
