### ISSUE TITLE
Managed node groups not being set to specified node_machine_type

### ISSUE THREAD

**Issue by marsdalesa** [jenkins-x/terraform-aws-eks-jx#248]
### Summary 
Managed nodes do not follow the instance type as set by `node_machine_type`, the [terraform-aws-eks module](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/a26c9fd0c9c880d5b99c438ad620e91dda957e10/modules/node_groups/node_groups.tf#L18) expects the provided variable to be `instance_types`, not `instance_type` and further, expects it to be of type `list(string)` and not `string`.

Due to this, the node_machine_type setting is ignored and instances are created as `m4.large`

### Steps to reproduce the behavior

Create cluster using this module, supplying `node_machine_type = "m5.large"` (this is actually the [default](https://github.com/jenkins-x/terraform-aws-eks-jx/blob/2a9c59a870960cff2ed28ca8ac20cfef246bad40/modules/cluster/variables.tf#L32) for the variable and is ignored)

### Expected behavior

Cluster to install with managed node group containing EC2 instances matching the specified `node_machine_type`

### Actual behavior

Instances default to `m4.large` type as specified in [terraform-aws-eks module](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/a26c9fd0c9c880d5b99c438ad620e91dda957e10/local.tf#L42)

### Terraform version

The output of `terraform version` is:

```
Terraform v0.14.6
```

### Module version

1.15.10

### Operating system

Ubuntu 20.10

**Comment by ankitm123** [comment]
> the terraform-aws-eks module expects the provided variable to be instance_types, not instance_type and further, expects it to be of type list(string) and not string

yeah, need to use a separate variable for the node group type, cannot re-use the one used for self managed worker groups, hmm.

**Comment by cpsburca** [comment]
Any updates on this

**Comment by marsdalesa** [comment]
I haven't spoken to Ankit for a bit, I'll check in with him later and possibly make a PR using a separate variable for this as per his comment. If you are running terraform locally and want to hack this to get up and running, after running `terraform init` you could edit `.terraform/modules/eks-jx/modules/cluster/main.tf` and just set [this line](https://github.com/jenkins-x/terraform-aws-eks-jx/blob/24f7e326e44e1d4326eabc08e6adee7ccc18283a/modules/cluster/main.tf#L134) to `instance_types   = [var.node_machine_type]`

**Comment by marsdalesa** [comment]
> I think it's not the only one problem, as the variable is string but it should be a list.

Yep, that's why the hack I gave uses `[]`. I do believe the intention of it being a list was for spot instances - which weren't applicable to managed node groups (until December 2020) but that would require further work upstream if it hasn't been done and yeah - would have to be factored into any PR here.

**Comment by cpsburca** [comment]
Even after fixing the module and all related variables the node_instance_type is the same. Is even not the default one from variables from the module (m5.large is defined but it's creating m4.large). From what I see this variable is used only for self-managed nodes.
Output from terraform plan:
```
 # module.eks-jx.module.cluster.module.eks.module.node_groups.aws_eks_node_group.workers["eks-jx-node-group"] will be created
  + resource "aws_eks_node_group" "workers" {
      + ami_type        = "AL2_x86_64"
      + arn             = (known after apply)
      + capacity_type   = (known after apply)
      + cluster_name    = "cp-dev"
      + disk_size       = 10
      + id              = (known after apply)
      + instance_types  = [
          + "m4.large",
        ]
```
