### ISSUE TITLE
Cannot import existing eks cluster with uppercase characters.

### ISSUE THREAD

**Issue by KaKeimei** [jenkins-x/terraform-aws-eks-jx#251]
### Summary 

I tried to use an existing eks cluster. It contains uppercase alphabet characters. While creating s3 resources,  I got an error that says something like bucket names must not contain uppercase characters 

### Steps to reproduce the behavior

Create an eks cluster with uppercase chars.
Import this cluster into jx module.

### Expected behavior

successfully create jx module.

### Actual behavior

Terraform fails on creating s3 bucket

### Terraform version

The output of `terraform version` is:

```
Terraform v0.14.6

Your version of Terraform is out of date! The latest version
is 0.14.8. You can update by downloading from https://www.terraform.io/downloads.html
```

### Operating system

maxos

**Comment by ankitm123** [comment]
Makes sense, s3 bucket names cannot have uppercase characters. See: https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html. We should convert the upper case eks cluster name to lower case before naming the buckets.
