### ISSUE TITLE
Cluster Accessing Issue

### ISSUE THREAD

**Issue by zakswindow** [jenkins-x/terraform-aws-eks-jx#28]
Hi guys,

I need some help here please. 
@hferentschik  @jstrachan 
**First question:**

It seems like I have to create a separate IAM user for vault. Is there any way I can provide I am role? This is very inconvenient because lot of users manage cross accounts with IAM roles.

I use aws-vault profiles to create resources in aws. After creating eks cluster I can not access it, do you only allow vault IAM user to access the cluster? Is there anyway I can output configmap using your module? Or I can inject IAM role into this module so that when I can use aws-vault with IAM role and I will be able to access eks cluster and k8s dashboard?

If I need to use Vault User then it will be a nightmare. I have to create Access key and Secret key only for that account where I have EKS cluster. This breaks the whole best practices. IAM users are centralized from one root account. Creating additional IAM user in a separate account where EKS cluster is, actually it makes the whole thing a little difficult.

**second question:**

I still want to use Jenkins X Old server, don't want to use Prow because lot of our developers still using classic version. How do I make sure this module is installing https://github.com/jenkins-x/jx/releases/tag/v2.0.1286,This is the last release with perfect support for classic Jenkins server. From 2.1.1 Jenkins server is being removed. 

This module is using this template https://github.com/jenkins-x/jenkins-x-versions, ref is master and webhook is prow. Which tag shall I use for old Jenkins server?
Please advise. Thank you very much.

**Comment by hferentschik** [comment]
> It seems like I have to create a separate IAM user for vault. Is there any way I can provide I am role? This is very inconvenient because lot of users manage cross accounts with IAM roles.

Unfortunately, for now, you need this additional IAM user. With this pull request - https://github.com/jenkins-x/terraform-aws-eks-jx/pull/26 - the user gets created for you. Whether this is an option for you, I don't know. 

The underlying problem is a Vault issue. We already submitted a pull request for Vault which is merged, just not released yet. See https://github.com/jenkins-x/terraform-aws-eks-jx/issues/20 for more details. Once a Vault version with this fix is available we will update the module.

> After creating eks cluster I can not access it, do you only allow vault IAM user to access the cluster

Nope. You should get connected to the cluster. Your kubeconfig should be updated after running Terraform. Can you provide some more context?

> If I need to use Vault User then it will be a nightmare. I have to create Access key and Secret key only for that account where I have EKS cluster. This breaks the whole best practices. IAM users are centralized from one root account. Creating additional IAM user in a separate account where EKS cluster is, actually it makes the whole thing a little difficult.

Agreed. The Vault user approach is a workaround for now. See above.

**Comment by hferentschik** [comment]
> I still want to use Jenkins X Old server, don't want to use Prow because lot of our developers still using classic version. How do I make sure this module is installing https://github.com/jenkins-x/jx/releases/tag/v2.0.1286,This is the last release with perfect support for classic Jenkins server. From 2.1.1 Jenkins server is being removed.

Not sure tbh. Classic Jenkins is deprecated and this Terraform module is targeting `jx boot` and Tekton + Prow + ...
If you want to use Classic Jenkins your best bet might be to use `jx create cluster` from version `v2.0.1286`, but I am not sure. You could also try to create the cluster using this module and then run `jx install cluster` with this older version of `jx`.

**Comment by zakswindow** [comment]
> > It seems like I have to create a separate IAM user for vault. Is there any way I can provide I am role? This is very inconvenient because lot of users manage cross accounts with IAM roles.
> h
> Unfortunately, for now, you need this additional IAM user. With this pull request - #26 - the user gets created for you. Whether this is an option for you, I don't know.
> 
> The underlying problem is a Vault issue. We already submitted a pull request for Vault which is merged, just not released yet. See #20 for more details. Once a Vault version with this fix is available we will update the module.
> 
> > After creating eks cluster I can not access it, do you only allow vault IAM user to access the cluster
> 
> Nope. You should get connected to the cluster. Your kubeconfig should be updated after running Terraform. Can you provide some more context?
> 
> > If I need to use Vault User then it will be a nightmare. I have to create Access key and Secret key only for that account where I have EKS cluster. This breaks the whole best practices. IAM users are centralized from one root account. Creating additional IAM user in a separate account where EKS cluster is, actually it makes the whole thing a little difficult.
> 
> Agreed. The Vault user approach is a workaround for now. See above.

**Comment by zakswindow** [comment]
> > It seems like I have to create a separate IAM user for vault. Is there any way I can provide I am role? This is very inconvenient because lot of users manage cross accounts with IAM roles.
> 
> Unfortunately, for now, you need this additional IAM user. With this pull request - #26 - the user gets created for you. Whether this is an option for you, I don't know.
> 
**Are you saying additional user should be used to run terraform apply command?** But an existing user is required to create all module resources. I am using cross-account user and role to create eks cluster. Module is creating IAM user, to access KMS, Dynamodb etc while jx boot command is running. Is this IAM user for something else too?

> The underlying problem is a Vault issue. We already submitted a pull request for Vault which is merged, just not released yet. See #20 for more details. Once a Vault version with this fix is available we will update the module.
> 
Thank you very much. What's the ETA on this release please? It will be very helpful. Vault is breaking jx boot installation process. I am trying lots of workarounds but no success yet. 

> > After creating eks cluster I can not access it, do you only allow vault IAM user to access the cluster
> 
> Nope. You should get connected to the cluster. Your kubeconfig should be updated after running Terraform. Can you provide some more context?
> 
Yes I am able to access cluster with cross-account user which I have used to create EKS in the first place with the module. jx boot try to create access key and secret key for new IAM user. i have an exiting pair of access key and secret on shell already which was exported by aws-vault. I am confused because I don't know what is the new IAM user exactly for. Do I need it for terraform commands or just for jx boot command? Not clear, sorry. Once you use exiting user, EKS can be accessed by that user automatically unless you update configmap with other users or roles. Do I need to add the new IAM user to auth configmap and then run jx boot command to make it work? At the moment I get this when I run jx boot - (existing user profile on shell)

`Waiting for vault to be initialized and unsealed...
Waiting for vault to be initialized and unsealed...
Waiting for vault to be initialized and unsealed...
Waiting for vault to be initialized and unsealed...`


> 

It repeats with installing vault-operator...

> > If I need to use Vault User then it will be a nightmare. I have to create Access key and Secret key only for that account where I have EKS cluster. This breaks the whole best practices. IAM users are centralized from one root account. Creating additional IAM user in a separate account where EKS cluster is, actually it makes the whole thing a little difficult.
> 
> 
> Agreed. The Vault user approach is a workaround for now. See above.
> 
Please can you help to understand about vault user? When exactly this user required? Does it work when I use aws-vault in the background. 
1. shall I create terraform resources with the existing user?
2. and then shall I update auth ConfigMap to add newly created IAM user?
3. which use shall I use to run jx boot command?

**Comment by zakswindow** [comment]
> > I still want to use Jenkins X Old server, don't want to use Prow because lot of our developers still using classic version. How do I make sure this module is installing https://github.com/jenkins-x/jx/releases/tag/v2.0.1286,This is the last release with perfect support for classic Jenkins server. From 2.1.1 Jenkins server is being removed.
> 
> Not sure tbh. Classic Jenkins is deprecated and this Terraform module is targeting `jx boot` and Tekton + Prow + ...
> If you want to use Classic Jenkins your best bet might be to use `jx create cluster` from version `v2.0.1286`, but I am not sure. You could also try to create the cluster using this module and then run `jx install cluster` with this older version of `jx`.

According to the documentation, I can still use webhook: Jenkins with latest release 2.086. I am using old Jenkins version. Shouldn't this work?

**Comment by zakswindow** [comment]
This module does not work with the vault. Vault is an indefinite loop, it's a blocker. I tried so much but almost gave up. Vault needs to be fixed, then probably everything will work. @hferentschik 

`Vault operator installed in namespace jx
Applying vault ingress in namespace jx for vault name jx-vault-rose
ingress.extensions/jx-vault-rose created
**WARNING: Vault.AutoCreate is false but required property secretAccessKey is missing**
Some of the required provided values are empty - We will create all resources
Creating vault resources with following values, eu-west-1, eks@ree.uk, vault-data, vault-unseal-20200423013036257
Vault CloudFormation stack created
You can watch progress in the CloudFormation console: https://console.aws.amazon.com/cloudformation/home?region=eu-west-1#/stacks/stackinfo?stackId=arn:aws:cloudformation:eu-west-1:47474744747:stack/jenkins-x-vault-stackf964b73/44bb690-852f-11ea-af1b-49202hgbe28da
Creating secret access keys
Vault 'jx-vault-montrose' in namespace 'jx' updated

STEP: create-helm-values command: /bin/sh -c jx step create values --name parameters in dir: /Users/xyz/ree/infrastructure-as-code/terraform/staging/eks/jenkins-x-boot-config/env

WARNING

Traditional Jenkins masters are being deprecated and removed from all new Jenkins X releases starting on April 20, 2020.
We strongly recommend using the default Tekton-based configuration instead for all Jenkins X activity going forward. We do not recommend using the Jenkins X workflow based around Jenkins masters.

For more information: https://jenkins-x.io/blog/2020/03/11/tekton/
defaulting to secret storage scheme vault found from requirements file at /Users/xyz/ree/infrastructure-as-code/terraform/ystaging/eks/jenkins-x-boot-config/jx-requirements.yml
defaulting to secret base path to the cluster name montrose found from requirements file at /Users/xyz/ree/infrastructure-as-code/terraform/staging/eks/jenkins-x-boot-config/jx-requirements.yml
generated schema file /Users/xyz/ree/infrastructure-as-code/terraform/staging/eks/jenkins-x-boot-config/env/parameters.schema.json from template /Users/xyz/ree/nfrastructure-as-code/terraform/staging/eks/jenkins-x-boot-config/env/parameters.tmpl.schema.json
Waiting for vault to be initialized and unsealed...
Waiting for vault to be initialized and unsealed...
Waiting for vault to be initialized and unsealed...`

**Comment by zakswindow** [comment]
@hferentschik Maybe it will be helpful to debug, I checked vault logs and I saw this:

> Using eth0 for VAULT_CLUSTER_ADDR: https://10.4.40.200:8201
> telemetry.disable_hostname has been set to false. Recommended setting is true for Prometheus to avoid poorly named metrics.
> Error initializing storage of type dynamodb: UnrecognizedClientException: The security token included in the request is invalid.
> 	status code: 400, request id: FPNO3296NI0LK6MNROMJPON5KNVV4KQNSO5AEMVJF66Q9ASUAAJG
