### ISSUE TITLE
Feature request: Add map_accounts, map_roles and map_users

### ISSUE THREAD

**Issue by zakswindow** [jenkins-x/terraform-aws-eks-jx#29]
If I use terraform eks module https://github.com/terraform-aws-modules/terraform-aws-eks, I can add additional IAM account, IAM role or IAM users. This will simplify accessing k8s Dashboard. 

Is it possible to add this feature to JX module please?

**Example:**
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/2fd078e7c1c9df29c6c7a90989060bf84075af9d/examples/basic/main.tf

**Comment by hferentschik** [comment]
@zakswindow, I am not quite sure what you are asking here. Can you please provide some more context? 

Under the hood this module already uses terraform-aws-eks (https://github.com/jenkins-x/terraform-aws-eks-jx/blob/master/modules/cluster/main.tf#L54). What should we in your opnion do? Expose some more functionality from terraform-aws-eks from this module? Change some configuration?

**Comment by zakswindow** [comment]
> @zakswindow, I am not quite sure what you are asking here. Can you please provide some more context?
> 
> Under the hood this module already uses terraform-aws-eks (https://github.com/jenkins-x/terraform-aws-eks-jx/blob/master/modules/cluster/main.tf#L54). What should we in your opnion do? Expose some more functionality from terraform-aws-eks from this module? Change some configuration?

Please see this link here https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/examples/basic/main.tf

`  map_roles                            = var.map_roles
  map_users                            = var.map_users
  map_accounts                         = var.map_accounts`
If we can add this vars to jx eks module to add some additional users to configmap/aws-auth, we then don't need to add vault user manually.

**Comment by patrickleet** [comment]
@hferentschik 
`map_users` would be useful for sure

Looks like we just need a new variable here: https://github.com/jenkins-x/terraform-aws-eks-jx/blob/master/modules/cluster/variables.tf

And to pass it in here: https://github.com/jenkins-x/terraform-aws-eks-jx/blob/master/modules/cluster/main.tf#L55

That way we can use jx module like so:

```terraform
module "eks-jx" {
  source  = "jenkins-x/eks-jx/aws"
  // ...
  map_users = [
    {
      userarn  = aws_iam_user.patrick.arn
      username = aws_iam_user.patrick.name
      groups   = ["system:masters"]
    }
  ]
}

resource "aws_iam_user" "patrick" {
  name = "patrick"
}
```

**Comment by patrickleet** [comment]
It's also worth noting that currently, we can't add new users to aws-auth configmap, because any future terraform plan and apply's wipe out the changes.
