### ISSUE TITLE
Support supplying values to git-operator chart

### ISSUE THREAD

**Issue by msvticket** [jenkins-x/terraform-aws-eks-jx#303]
### Summary 

It would be good if you could supply values to the git-operator chart. 

My use case is that I need to supply the annotation eks.amazonaws.com/role-arn to sa jx-boot-job.

**Comment by ankitm123** [comment]
I think the simplest solution would be to do what we do for the nginx helm chart, and provide values.yaml file. See: https://github.com/jenkins-x/terraform-aws-eks-jx/blob/master/modules/nginx/main.tf#L9

**Comment by msvticket** [comment]
I looked at the nginx model and I don't think that is a good idea, because that means that the user needs to supply all values.

**Comment by ankitm123** [comment]
I think that is more flexible, else we have 100 different use cases and then it becomes hard to make everyone happy :grimacing: . You can just give them a few values as template, and let them add more ... 
>user needs to supply all values.
You can also do a hybrid approach - set some common values using ser and then also give users the ability to use values.yaml.
