### ISSUE TITLE
Alternate approach for IRSA

### ISSUE THREAD

**Issue by gazal-k** [jenkins-x/terraform-aws-eks-jx#31]
I realise that this repo creates IAM Roles and also the ServiceAccounts in k8s linking those IAM Roles.
So let's say we create the following SAs:

`jx:tekton-bot`
`jx:exdns-external-dns`
`jx:cm-cert-manager`

etc

Now the helm charts for tekton, external-dns, cert-manager etc also have their SA resource defined. When using JX with helm2 the way charts are applied are something like:

```sh
helm template --name release-name prefix/chart-name | kubectl apply -f
```

Any existing resources are updated. So far so good.

When we start using helm 3 though, I believe it will be just `helm install` that we use. When using `helm install`, helm manages all the resources defined in a chart. Install fails if a resource defined in a chart already exists.

Now this can be solved in one of 2 ways:
1. Continue creating SA using terraform or whatever cloud tooling people use and set values for the chart to skip creating SA.
2. Don't create SA using cloud tooling, let helm create and manage SA

What I'm recommending is approach 2. The idea is to manage as much k8s resources using the helm based GitOps workflow as possible and let the cloud tooling create just resources outside of it. 

With approach 2, we'll need to annotate SAs with the role ARN though. But this I think is consistent with the approach being taken for GCP; https://github.com/jenkins-x-labs/jenkins-x-versions/commit/6c7845a4c794601563da6c50d1fa68f56e7499f4, https://github.com/jenkins-x-labs/jenkins-x-versions/commit/44874e0813916d86f4a38322cf9d571351f2ebe4 etc.

Please provide feedback

**Comment by hferentschik** [comment]
I actually agree that in the long term it would be better to let Helm manage most of the Kubernetes specific resources, at the very least the namespaces, but maybe/probably also the Kubernetes service accounts. 

That said, right now we are targeting the current `jx boot` and `jx steep helm apply` (using Helm 2) setup. It is not yet decided if, when and how any Labs work will be integrated. So I'd prefer to cross that bridge when we look at Helm 3 as a whole. Does that make sense?

**Comment by gazal-k** [comment]
Of course. I'm only suggesting this for when integrating with helm 3. Just putting this here so that we don't lose what we learnt from the labs
