### ISSUE TITLE
new versions of cluster autoscaler require more actions

### ISSUE THREAD

**Issue by danjmccay** [jenkins-x/terraform-aws-eks-jx#348]
https://github.com/jenkins-x/terraform-aws-eks-jx/blob/4240b95efe7558de35eb195d4b3ad76fbe9d0f20/modules/cluster/irsa.tf#L280

It seems that the latest versions of cluster autoscaler require these additional actions to be allowed:
ec2:DescribeInstanceTypes
autoscaling:DescribeInstances

**Comment by msvticket** [comment]
This is fixed by #357 and released in v1.21.1
