### ISSUE TITLE
JX Boot Error: Waiting for vault to be initialized and unsealed

### ISSUE THREAD

**Issue by zakswindow** [jenkins-x/terraform-aws-eks-jx#37]
@hferentschik I really need some help. I am having this issue for a while now. I am trying everything I can but I can't seem to fix it.

Steps to reproduce:

I am using eu-west-2 and I have existing Route 53 Zone which i am using as apex_domain

1. Clone eks-jx module and then created a TF file to refer the module
```
module "eks-jx" {
  source = "../aws-eks-jx/"

  vault_user                     = var.vault_iam_user
  enable_external_dns            = true
  cluster_name                   = var.cluster_name
  desired_node_count             = "2"
  max_node_count                 = "3"
  min_node_count                 = "2"
  enable_tls                     = true
  region                         = var.region
  node_machine_type              = var.ec2_type
  enable_logs_storage            = true
  enable_reports_storage         = true
  enable_repository_storage      = true
  apex_domain                    = var.apex_domain
  tls_email                      = var.tls_email
  vpc_name                       = var.cluster_name
  vpc_cidr_block                 = "10.5.0.0/16"
  vpc_subnets = [
    "10.5.1.0/24",
    "10.5.2.0/24",
    "10.5.3.0/24"
  ]

}
```

2. I have used admin account to run:
``` terraform apply```
Terraform was successfully finished without any error. jx-requirements.yml is created.

3. I have then updated config map for kube-system configmap/aws-auth to make sure  IAM user jenkins-x-vault can access the cluster. **(without updating configmap you can't run jx boot command, it will fail)**

4. I want to use **webhook: Jenkins** (still planning to use Jenkins X Server) so, I have changed jx-requirements.yml file.
```
versionStream:
  ref: master
  url: https://github.com/jenkins-x/jenkins-x-versions.git
webhook: jenkins
```

So this is how my jx-requirements.yml file looks like:

```
autoUpdate:
  enabled: false
  schedule: ""
terraform: true
cluster:
  clusterName: "eks-cluster"
  environmentGitOwner: ""
  provider: eks
  region: "eu-west-2"
gitops: true
environments:
  - key: dev
  - key: staging
  - key: production
ingress:
  domain: "y.uk."
  ignoreLoadBalancer: true
  externalDNS: true
  tls:
    email: "x@y.com"
    enabled: true
    production: false
kaniko: true
secretStorage: vault
vault:
  aws:
    iamUserName: "jenkins-x-vault"
    dynamoDBTable: "vault-unseal-eks-cluster-92qpWWPP"
    dynamoDBRegion: "eu-west-2"
    kmsKeyId: "f1a00000-f9e1-4a8f-ya99-01fr001d6574"
    kmsRegion: "eu-west-2"
    s3Bucket: "vault-unseal-eks-cluster-88888000000111234500000008"
    s3Region: "eu-west-2"
storage:
  logs:
    enabled: true
    url: s3://logs-eks-cluster-88888000000111234500000008
  reports:
    enabled: true
    url: s3://reports-eks-cluster-88888000000111234500000008
  repository:
    enabled: true
    url: s3://repository-eks-cluster-88888000000111234500000008
versionStream:
  ref: master
  url: https://github.com/jenkins-x/jenkins-x-versions.git
webhook: jenkins
```
5. I have then exported keys for **jenkins-x-vault** IAM user
``` 
export VAULT_AWS_ACCESS_KEY_ID=<access key id>
export VAULT_AWS_SECRET_ACCESS_KEY=<secret key>
```
I did run "printenv" to make sure parameters are set properly

6. I have created empty directory jxboot, cd jxboot and I have run command: 
``` jx boot --requirements ../jx-requirements.yml ```

It did ask for:
```
Do you want to clone the Jenkins X Boot Git repository? [? for help] (Y/n)
```
I pressed Y

- I have then provided Git owner name, git username
Then, it asked me:
```
Would you like to upgrade to the jx version? [? for help] (Y/n)
```
I pressed No because I am using the following Jenkins X version:
```
CLI packages kubectl, git, helm seem to be setup correctly
NAME               VERSION
jx                 2.0.1286
Kubernetes cluster v1.15.11-eks-af3caf
kubectl            v1.16.9
git                2.20.1 (Apple Git-117)
```
jx 2.0.1286 was the latest Jenkis X server release.

After that, jx boot started to install the resources in the cluster. 

It takes very long time to seal the vault, and errors out, see below:
```
Waiting for vault to be initialized and unsealed...
Waiting for vault to be initialized and unsealed...
error: creating system vault URL client: wait for vault to be initialized and unsealed: reading vault health: Get https://vault-jx.y.uk/v1/sys/health?drsecondarycode=299&performancestandbycode=299&sealedcode=299&standbycode=299&uninitcode=299: dial tcp: lookup vault-jx.y-tree.uk on 55.37.0.2:53: no such host
error: failed to interpret pipeline file /Users/zak/y/infrastructure-as-code/terraform/staging/eks/jxboot/jenkins-x-boot-config/jenkins-x.yml: failed to run '/bin/sh -c jx step create values --name parameters' command in directory '/Users/zak/y/infrastructure-as-code/terraform/staging/eks/jxboot/jenkins-x-boot-config/env', output: ''
```
I installed Dashboard.

I checked logs for jx-vault-montrose-0 pod and it shows this:

```
Using eth0 for VAULT_CLUSTER_ADDR: https://10.5.3.57:8201
telemetry.disable_hostname has been set to false. Recommended setting is true for Prometheus to avoid poorly named metrics.
==> Vault server configuration:
           AWS KMS KeyID: cf309c7d-d9bd-4169-aeab-b962cb15d44b
          AWS KMS Region: eu-west-2
               Seal Type: awskms
             Api Address: http://jx-vault-montrose.jx:8200
                     Cgo: disabled
              Listener 1: tcp (addr: "0.0.0.0:8200", max_request_duration: "1m30s", max_request_size: "33554432", tls: "disabled")
               Log Level: info
                   Mlock: supported: true, enabled: true
           Recovery Mode: false
                 Storage: dynamodb (HA available)
                 Version: Vault v1.3.4
==> Vault server started! Log data will stream in below:
2020-04-29T02:34:15.481Z [INFO]  proxy environment: http_proxy= https_proxy= no_proxy=
2020-04-29T02:34:15.652Z [INFO]  core: stored unseal keys supported, attempting fetch
2020-04-29T02:34:15.656Z [WARN]  failed to unseal core: error="stored unseal keys are supported, but none were found"
2020-04-29 02:34:16.582632 I | [ERR] Error flushing to statsd! Err: write udp 127.0.0.1:56532->127.0.0.1:9125: write: connection refused
2020-04-29T02:34:16.657Z [INFO]  core: security barrier not initialized
2020-04-29T02:34:17.170Z [WARN]  core: stored keys supported on init, forcing shares/threshold to 1
2020-04-29T02:34:17.177Z [INFO]  core: security barrier not initialized
2020-04-29T02:34:17.195Z [INFO]  core: security barrier initialized: stored=1 shares=1 threshold=1
2020-04-29T02:34:17.279Z [INFO]  core: post-unseal setup starting
2020-04-29T02:34:17.306Z [INFO]  core: loaded wrapping token key
2020-04-29T02:34:17.306Z [INFO]  core: successfully setup plugin catalog: plugin-directory=
2020-04-29T02:34:17.313Z [INFO]  core: no mounts; adding default mount table
2020-04-29T02:34:17.324Z [INFO]  core: successfully mounted backend: type=cubbyhole path=cubbyhole/
2020-04-29T02:34:17.324Z [INFO]  core: successfully mounted backend: type=system path=sys/
2020-04-29T02:34:17.324Z [INFO]  core: successfully mounted backend: type=identity path=identity/
2020-04-29T02:34:17.388Z [INFO]  core: successfully enabled credential backend: type=token path=token/
2020-04-29T02:34:17.388Z [INFO]  core: restoring leases
2020-04-29T02:34:17.388Z [INFO]  rollback: starting rollback manager
2020-04-29T02:34:17.395Z [INFO]  expiration: lease restore complete
2020-04-29T02:34:17.413Z [INFO]  identity: entities restored
2020-04-29T02:34:17.417Z [INFO]  identity: groups restored
2020-04-29T02:34:17.455Z [WARN]  core: post-unseal upgrade seal keys failed: error="no recovery key found"
```

I can not see any subdomain created in existing Route53 zone.

Any idea what is going wrong please? I am running out ideas now.

**Comment by demiangmz** [comment]
Hi, I am also getting this error, my setup:

```
CLI packages kubectl, git, helm seem to be setup correctly
NAME               VERSION
jx                 2.1.10
Kubernetes cluster v1.15.11-eks-af3caf
kubectl            v1.16.0
git                2.17.1
```

I am using an existing IAM user for Vault and getting this error:

```
Waiting for vault to be initialized and unsealed...
Waiting for vault to be initialized and unsealed...
Waiting for vault to be initialized and unsealed...

Vault operator installed in namespace jx
Applying vault ingress in namespace jx for vault name jx-vault-tf-eks-demo
ingress.extensions/jx-vault-tf-eks-demo unchanged
Vault 'jx-vault-tf-eks-demo' in namespace 'jx' updated
error: unable to create/update Vault: waiting for vault service: service jx-vault-tf-eks-demo never became ready
error: failed to interpret pipeline file jenkins-x.yml: failed to run '/bin/sh -c jx step boot vault --provider-values-dir ../../kubeProviders' command in directory 'systems/vault', output: ''
```

**Comment by hferentschik** [comment]
Just some questions/pointers related to Terraform. As mentioned, we don't really test this setup. If you want to stay on static Jenkins I would think your better option is to use `jx create cluster`.

That said:

> I have then updated config map for kube-system configmap/aws-auth to make sure IAM user jenkins-x-vault can access the cluster. (without updating configmap you can't run jx boot command, it will fail)

That sounds odd. What is the error on this case? The IAM user is used by Vault to get the unseal keys. So I am not sure how this would relate to a ConfigMap.

Have you tried to use no DNS to start with? If you don't set the domain, nip.io should be used. Trying that might help to isolate the problem.

**Comment by zakswindow** [comment]
> Just some questions/pointers related to Terraform. As mentioned, we don't really test this setup. If you want to stay on static Jenkins I would think your better option is to use `jx create cluster`.
> 
> That said:
> 
> > I have then updated config map for kube-system configmap/aws-auth to make sure IAM user jenkins-x-vault can access the cluster. (without updating configmap you can't run jx boot command, it will fail)
> 
> That sounds odd. What is the error on this case? The IAM user is used by Vault to get the unseal keys. So I am not sure how this would relate to a ConfigMap.
> 
You need to have an IAM user to create was resources, how can you create resources without having an existing IAM user in the first place? EKS terraform module adds current IAM user which was used to create resources to configmap/aws-auth.
If you want to use your IAM user which you're creating to install Jenkins x you need to update configmap/aws-auth otherwise it will show you an error"unauthorized".

But if you want users to create vault user and use vault user to create eks and install Jenkins x then you need this user from the beginning, before creating cluster. This problem can be solved if you allow us to add map roles to map users like terraform eks module does. Please check last few lines here https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/examples/basic/main.tf
Most of us already have existing management IAM users to manage was resources. Hope it's clear now.
> Have you tried to use no DNS to start with? If you don't set the domain, nip.io should be used. Trying that might help to isolate the problem.
>
I've fixed the issue with this line of code in jx-requirements.yaml: 
`autoCreate: true`

**Comment by zakswindow** [comment]
i found a workaround

**Comment by cristi-vlad** [comment]
> i found a workaround

What is that workaround ?
