### ISSUE TITLE
Cluster availability check in null_resource.wait_for_cluster fails to detect when the cluster becomes available

### ISSUE THREAD

**Issue by supermodo** [jenkins-x/terraform-aws-eks-jx#52]
I get the same behavior of https://github.com/terraform-aws-modules/terraform-aws-eks/issues/757

```
module.eks-jx.module.cluster.module.eks.null_resource.wait_for_cluster[0]: Still creating... [23m20s elapsed] 
module.eks-jx.module.cluster.module.eks.null_resource.wait_for_cluster[0] (local-exec): /bin/sh: wget: command not found
```

Perhaps aws-eks dependency is outdated and the problem is solved in [750](https://github.com/terraform-aws-modules/terraform-aws-eks/pull/750), but the [workaround](https://github.com/terraform-aws-modules/terraform-aws-eks/issues/757#issuecomment-623434072) is not working because the input `wait_for_cluster_cmd` is not exposed in eks-jx.

Any suggestion?

**Comment by supermodo** [comment]
Sorry, I've missed the `wget: command not found`
I've installed [wget](https://www.gnu.org/software/wget/) and is working :-)

**Comment by faceleg** [comment]
@supermodo  how did you install wget?
