### ISSUE TITLE
terraform destory fails on internet gateway and public subnet deletion

### ISSUE THREAD

**Issue by ankitm123** [jenkins-x/terraform-aws-eks-jx#54]
Terraform destroy gets stuck on deleting public subnet and eventually times out:
```
Error: Error deleting subnet: timeout while waiting for state to become 'destroyed' (last state: 'pending', timeout: 20m0s)

Error: Error deleting subnet: timeout while waiting for state to become 'destroyed' (last state: 'pending', timeout: 20m0s)

Error: Error waiting for internet gateway (igw-040fd33822a0369a0) to detach: timeout while waiting for state to become 'detached' (last state: 'detaching', timeout: 15m0s)

Error: Error deleting subnet: timeout while waiting for state to become 'destroyed' (last state: 'pending', timeout: 20m0s)
```
The way to get around this is to delete the Load balancer (and check all the ENIs are deleted), and then re-run `terraform destroy`. May be this can be handled better in the module?

**Comment by andrewhoplife** [comment]
This is also true for the ASG groups, Launch Configuration, ESK cluster, VPC.

**Comment by ankitm123** [comment]
it seems that I have to terminate the ec2 instances as well to make terraform destroy work, starting to think this has to do with EKS not having proper permissions to manage the resources. Will take a look this weekend.

**Comment by andrewhoplife** [comment]
I just noticed upgrading to TF v0.12.26 fixed the delete function for me, much better!

**Comment by ankitm123** [comment]
https://github.com/jenkins-x/terraform-aws-eks-jx/issues/122#issuecomment-678796285

/close

**Comment by domhdp** [comment]
I had this problem even with Terraform v0.13.0. The `terraform destroy` was stuck and couldn't delete the subnets or the internet gateway.

I manually deleted the NLB that had been created, and then re-ran the `terraform destroy` and then the project was deleted successfully.

**Comment by lokinegalur** [comment]
enable_deletion_protection = false this solves the problem
