### ISSUE TITLE
terraform destroy does not delete non-empty buckets

### ISSUE THREAD

**Issue by ankitm123** [jenkins-x/terraform-aws-eks-jx#56]
Terraform destroy does not delete non-empty s3 buckets. 
```
Error: error deleting S3 Bucket (vault-unseal-tf-jx-grand-leopard-20200510193244396100000005): BucketNotEmpty: The bucket you tried to delete is not empty. You must delete all versions in the bucket.
	status code: 409, request id: 410A09EDE43DF2A4, host id: PYpRJ6LZyL09cOGTXPQ/rURaQiJpZih58V/xssaHZOlN+b7zjBOGWokx6ukYHYLt5U6HeMlKgzs=
```
The way to delete them is to empty them in the aws s3 console, and then re-run terraform destroy. This can be fixed by setting:
```
force_destroy = true
```
when creating the s3 buckets

**Comment by vfarcic** [comment]
I'm still experiencing the same issue. Should we add `force_destroy` to the definition or it is now set by default? If it's former, I did not find that argument in https://jenkins-x.io/docs/install-setup/installing/create-cluster/eks/.

**Comment by hferentschik** [comment]
Let's open a new issue if there is still an issue. Re-opening a released issue causes issues with the changelog.

**Comment by hferentschik** [comment]
> Should we add force_destroy to the definition or it is now set by default

You need to explicitly add force_destroy, the default is false.

>  If it's former, I did not find that argument in https://jenkins-x.io/docs/install-setup/installing/create-cluster/eks/.

There is an update coming ...

**Comment by ankitm123** [comment]
My bad, never made the docs change, only readme :(
