### ISSUE TITLE
Tried to create resource record set but it already exists

### ISSUE THREAD

**Issue by andrewhoplife** [jenkins-x/terraform-aws-eks-jx#63]
The latest version of this repo creates the following error on the first terraform apply run:

```
Error: [ERR]: Error building changeset: InvalidChangeBatch: [Tried to create resource record set [name='jenkins.snip.', type='NS'] but it already exists]
	status code: 400, request id: 51ad7953-608c-4c8b-8520-49938db17ae8

  on modules/dns/main.tf line 17, in resource "aws_route53_record" "subdomain_ns_delegation":
  17: resource "aws_route53_record" "subdomain_ns_delegation" {
```

The domain did not exist prior to running. A re-run of the command also hard fails. Is there a way for this to soft fail on this step and continue executing?

Tested on TF v0.12.26 and v0.12.25.

**Comment by ankitm123** [comment]
I think you answered ur question in #73 :).

**Comment by andrewhoplife** [comment]
Agreed closing.
