### ISSUE TITLE
aws_eks_node_group

### ISSUE THREAD

**Issue by vfarcic** [jenkins-x/terraform-aws-eks-jx#66]
From what I saw, we are not using `aws_eks_node_group` for worker nodes. That was probably the most important improvement AWS did to EKS recently (e.g., 6 months ago). Is there a specific reason for that?

**Comment by ankitm123** [comment]
I will open a PR to add it, it's been in the back of my mind for some time :)

**Comment by ankitm123** [comment]
Also think that this should be the default type, instead of the normal worker group.
