### ISSUE TITLE
Expose variable to conditionally create eks cluster

### ISSUE THREAD

**Issue by ankitm123** [jenkins-x/terraform-aws-eks-jx#67]
This: https://github.com/terraform-aws-modules/terraform-aws-eks#conditional-creation
Also, when doing a terraform destroy if the cluster has been deleted, destroy fails because this variable is set to true by default and the module tries to query the datasource.

**Comment by ankitm123** [comment]
Another use case could be to install other resources required for jenkinsx in an existing cluster. Thoughts @hferentschik ?

**Comment by pparth** [comment]
> Another use case could be to install other resources required for jenkinsx in an existing cluster. Thoughts @hferentschik ?

Yes, generally in bigger companies, it is expected that such clusters are maintained by pure Ops Teams that enforce the security and compliance requirements needed to the cluster, especially at the network level. Platform Teams then should be able to use an existing EKS cluster to deploy and maintain the JX3 pieces along with some operational characteristics of the cluster like scaling etc.
