### ISSUE TITLE
Fresh run hard stops on subdomain ns delegation

### ISSUE THREAD

**Issue by andrewhoplife** [jenkins-x/terraform-aws-eks-jx#73]
Running terraform apply with the subdomain resource record creates a hard failure when the record gets created earlier in the run and hard stops the rest of the deployment.

```
Error: [ERR]: Error building changeset: InvalidChangeBatch: [Tried to create resource record set [name='jenkins.snip.', type='NS'] but it already exists]
	status code: 400, request id: cf01eaa7-e431-4049-a12a-a4bc351a126d

  on .terraform/modules/eks-jx/terraform-aws-eks-jx-1.0.5/modules/dns/main.tf line 17, in resource "aws_route53_record" "subdomain_ns_delegation":
  17: resource "aws_route53_record" "subdomain_ns_delegation" {
```

This is only resolved by setting create_and_configure_subdomain to false and performing terraform apply again.

**Comment by ankitm123** [comment]
Isn't this expected @andrewhoplife? The subdomain already exists, so when you try to create it again it complains. By setting `create_and_configure_subdomain` to false, u set the count to 0, thereby skipping the creating, and going further in terraform apply. 
The relevant code is:
```
resource "aws_route53_record" "subdomain_ns_delegation" {
  count   = var.create_and_configure_subdomain ? 1 : 0
  ....
```
Am I interpreting this wrong?

**Comment by andrewhoplife** [comment]
The subdomain did not exist prior to running the terraform apply. In order to get the run to complete the flag needs to be set to false and run again.
