### ISSUE TITLE
terraform init doesn't work with the example main.tf 

### ISSUE THREAD

**Issue by stabenfeldt** [jenkins-x/terraform-aws-eks-jx#77]
### Summary 
terraform init doesn't work with the example main.tf listed at https://jenkins-x.io/docs/getting-started/
It stops on 
```
Error: Failed to download module
```

### Steps to reproduce the behavior
```
terraform --version
# => Terraform v0.12.26
```
```
cat > main.tf

module "eks-jx" {
  source  = "jenkins-x/eks-jx/aws"
}

output "vault_user_id" {
  value       = module.eks-jx.vault_user_id
  description = "The Vault IAM user id"
}

output "vault_user_secret" {
  value       = module.eks-jx.vault_user_secret
  description = "The Vault IAM user secret"
}
```
```
terraform init
Initializing modules...
Downloading jenkins-x/eks-jx/aws 1.0.5 for eks-jx...

Error: Failed to download module

Could not download module "eks-jx" (main.tf:1) source code from
"https://github.com/jenkins-x/terraform-aws-eks-jx/archive/v1.0.5.tar.gz//*?archive=tar.gz":
bad response code: 404.


Error: Failed to download module

Could not download module "eks-jx" (main.tf:1) source code from
"https://github.com/jenkins-x/terraform-aws-eks-jx/archive/v1.0.5.tar.gz//*?archive=tar.gz":
bad response code: 404.
```
### Expected behavior

To download required modules without any errors.

### Operating system / Environment

Running on macOS Catalina 10.15.4 (19E287)

**Comment by munjalpatel** [comment]
I am also having the same issue. But only on Terraform Cloud.
On my local machine, `terraform init` works fine.

![image](https://user-images.githubusercontent.com/2717686/91387054-38872a80-e7e9-11ea-89ac-2da1a963bbb4.png)

**Comment by saikrishnamylaram** [comment]
/remove-lifecycle rotten
i'm also getting same issue unable to download modules


[0m[0mCould not download module "bastion_security_group" (security_groups.tf:5)
[31m│[0m [0msource code from
[31m│[0m [0m"git@gitlab.com:DXchange.io/devops/terraform-modules.git?ref=master": error
[31m│[0m [0mdownloading
[31m│[0m [0m'ssh://git@gitlab.com/DXchange.io/devops/terraform-modules.git?ref=master':
[31m│[0m [0m/usr/bin/git exited with 128: Cloning into
[31m│[0m [0m'.terraform/modules/bastion_security_group'...
[31m│[0m [0mremote: 
[31m│[0m [0mremote:
[31m│[0m [0m========================================================================
[31m│[0m [0mremote: 
[31m│[0m [0mremote: The project you were looking for could not be found or you don't
[31m│[0m [0mhave permission to view it.
[31m│[0m [0mremote: 
[31m│[0m [0mremote:
[31m│[0m [0m========================================================================
[31m│[0m [0mremote: 
[31m│[0m [0mfatal: Could not read from remote repository.
[31m│[0m [0m
[31m│[0m [0mPlease make sure you have the correct access rights
[31m│[0m [0mand the repository exists.
[31m│[0m [0m
[31m╵[0m[0m
[0m[0m

**Comment by ankitm123** [comment]
No idea, but ur logs show that it's trying to reach gitlab:
`[31m│�[0m �[0m"git@gitlab.com:DXchange.io/devops/terraform-modules.git?ref=master": error`

So something to do with ur internal network, and not this module.

**Comment by saikrishnamylaram** [comment]
I got solution for this error..i  Coped my private key to gitlab then it's
worked fine. Thanks
