### ISSUE TITLE
Cannot maximize Free Tier of DynamoDB

### ISSUE THREAD

**Issue by joebertj** [jenkins-x/terraform-aws-eks-jx#86]
The Free Tier for DynamoDB is 25 Read Capacity Units and 25 Write Capacity Units. The default settings for both is 2 RCU and 2 WCU. Need to adjust this to maximize free tier.

I will create a separate PR for this.

**Comment by hferentschik** [comment]
Some relevant information around DynamoDB pricing in this context - https://www.serverless.com/blog/dynamodb-on-demand-serverless/
