### ISSUE TITLE
part0-deployment.yaml": no matches for kind "Deployment" in version "extensions/v1beta1"

### ISSUE THREAD

**Issue by collabnix** [jenkins-x/terraform-aws-eks-jx#94]
## Pre-requisite
- Macbook
- brew tap jenkins-x/jx
- brew install jx

## Installing Jenkins X on EKS

```
jx create cluster eks --skip-installation
```
```
Missing required dependencies, deselect to avoid auto installing
- eksctl
- aws-iam-authenticator
- kubectl
- helm
```
## Installing eksctl

Downloading https://github.com/weaveworks/eksctl/releases/download/0.11.1/eksctl_Darwin_amd64.tar.gz to /Users/ajeetraina/.jx/bin/eksctl.tar.gz...
Downloaded /Users/ajeetraina/.jx/bin/eksctl.tar.gz
Installing aws-iam-authenticator
Downloading https://amazon-eks.s3-us-west-2.amazonaws.com/1.12.7/2019-03-27/bin/darwin/amd64/aws-iam-authenticator to /Users/ajeetraina/.jx/bin/aws-iam-authenticator...
Downloaded /Users/ajeetraina/.jx/bin/aws-iam-authenticator
Installing kubectl
Downloading https://storage.googleapis.com/kubernetes-release/release/v1.13.2/bin/darwin/amd64/kubectl to /Users/ajeetraina/.jx/bin/kubectl...
Downloaded /Users/ajeetraina/.jx/bin/kubectl
Installing helm
Downloading https://get.helm.sh/helm-v2.12.2-darwin-amd64.tar.gz to /Users/ajeetraina/.jx/bin/helm.tgz...
Downloaded /Users/ajeetraina/.jx/bin/helm.tgz
Installing helm secrets plugin
WARNING: Failed to retrieve team settings: failed to setup the dev environment for namespace 'default': the server could not find the requested resource (post environments.jenkins.io) - falling back to default settings...
Creating EKS cluster - this can take a while so please be patient...
You can watch progress in the CloudFormation console: https://console.aws.amazon.com/cloudformation/
[ℹ]  eksctl version 0.11.1
[ℹ]  using region us-east-2
[ℹ]  setting availability zones to [us-east-2a us-east-2b us-east-2c]
[ℹ]  subnets for us-east-2a - public:192.168.0.0/19 private:192.168.96.0/19
[ℹ]  subnets for us-east-2b - public:192.168.32.0/19 private:192.168.128.0/19
[ℹ]  subnets for us-east-2c - public:192.168.64.0/19 private:192.168.160.0/19
[ℹ]  nodegroup "ng-623234c1" will use "ami-082bb518441d3954c" [AmazonLinux2/1.14]
[ℹ]  using Kubernetes version 1.14
[ℹ]  creating EKS cluster "beautiful-creature-1591004252" in "us-east-2" region with un-managed nodes
[ℹ]  will create 2 separate CloudFormation stacks for cluster itself and the initial nodegroup
[ℹ]  if you encounter any issues, check CloudFormation console or try 'eksctl utils describe-stacks --region=us-east-2 --cluster=beautiful-creature-1591004252'
[ℹ]  CloudWatch logging will not be enabled for cluster "beautiful-creature-1591004252" in "us-east-2"
[ℹ]  you can enable it with 'eksctl utils update-cluster-logging --region=us-east-2 --cluster=beautiful-creature-1591004252'
[ℹ]  Kubernetes API endpoint access will use default of {publicAccess=true, privateAccess=false} for cluster "beautiful-creature-1591004252" in "us-east-2"
[ℹ]  2 sequential tasks: { create cluster control plane "beautiful-creature-1591004252", create nodegroup "ng-623234c1" }
[ℹ]  building cluster stack "eksctl-beautiful-creature-1591004252-cluster"
[ℹ]  deploying stack "eksctl-beautiful-creature-1591004252-cluster"

[✔]  EKS cluster "beautiful-creature-1591004252" in "us-east-2" region is ready

Initialising cluster ...
eks cluster created. Skipping Jenkins X installation.
```

```
[Captains-Bay]🚩 >  kubectl cluster-info
Kubernetes master is running at https://BE4A3B69D0229AE5AD01A0915EFFBD08.yl4.us-east-2.eks.amazonaws.com
CoreDNS is running at https://BE4A3B69D0229AE5AD01A0915EFFBD08.yl4.us-east-2.eks.amazonaws.com/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
[Captains-Bay]🚩 >
```

## Installing Jenkins X

```
[Captains-Bay]🚩 >  cat <<EOF > myvalues.yaml
> monocular:
>   api:
>     resources:
>       limits:
>         memory: 2Gi
>   mongodb:
>     mongodbDatabase: ""
> jenkins:
>   Master:
>     Cpu: "2000m"
>     Memory: "4096Mi"
> EOF
```

[Captains-Bay]🚩 >

## Installing Jenkins X

```
[Captains-Bay]🚩 >  jx install --provider=eks --default-environment-prefix=elotl-cloud
Command "install" is deprecated, it will be removed on Jun 1 2020. We now highly recommend you use jx boot instead. Please check https://jenkins-x.io/docs/getting-started/setup/boot/ for more details.
? Configured Jenkins installation type: Serverless Jenkins X Pipelines with Tekton
Namespace jx created
Context "iam-root-account@beautiful-creature-1591004252.us-east-2.eksctl.io" modified.
Git configured for user: jenkins-x-bot and email jenkins-x@googlegroups.com
Helm installed and configured
? No existing ingress controller found in the kube-system namespace, installing one: Yes
Using local value overrides file /Users/ajeetraina/myvalues.yaml
Using helm values file: /var/folders/mq/z4bncmrs28sbtktxpck2whcm0000gn/T/ing-values-766749713

Waiting for external loadbalancer to be created and update the nginx-ingress-controller service in kube-system namespace
External loadbalancer created
Waiting to find the external host name of the ingress controller Service in namespace kube-system with name jxing-nginx-ingress-controller

On AWS we recommend using a custom DNS name to access services in your Kubernetes cluster to ensure you can use all of your Availability Zones
If you do not have a custom DNS name you can use yet, then you can register a new one here: https://console.aws.amazon.com/route53/home?#DomainRegistration:
? Would you like to register a wildcard DNS ALIAS to point at this ELB address?  Yes

? Enter your custom domain that we can use to setup a Route 53 ALIAS record to point at the ELB host: a8ef316d4a40811ea9f560a448cc2ced-0bb0b6f20b00c479.elb.us-east-2.amazonaws.com
? Your custom DNS name:
```
unable to recognize "/var/folders/mq/z4bncmrs28sbtktxpck2whcm0000gn/T/helm-template-workdir-085682282/jenkins-x/output/namespaces/jx/jenkins-x-platform/charts/chartmuseum/templates/part0-deployment.yaml": no matches for kind "Deployment" in version "extensions/v1beta1"
unable to recognize "/var/folders/mq/z4bncmrs28sbtktxpck2whcm0000gn/T/helm-template-workdir-085682282/jenkins-x/output/namespaces/jx/jenkins-x-platform/charts/heapster/templates/part0-deployment.yaml": no matches for kind "Deployment" in version "extensions/v1beta1"
unable to recognize "/var/folders/mq/z4bncmrs28sbtktxpck2whcm0000gn/T/helm-template-workdir-085682282/jenkins-x/output/namespaces/jx/jenkins-x-platform/charts/jenkins/templates/part0-jenkins-master-deployment.yaml": no matches for kind "Deployment" in version "extensions/v1beta1"'
```

**Comment by collabnix** [comment]
Closing this issue as I am not using terraform for this setup.

**Comment by ankitm123** [comment]
Not the right repository to open this issue @collabnix. You should open it in the main jx repo (https://github.com/jenkins-x/jx/issues)and close this . You are not using the terraform repo to create the cluster (any reason why?). I would suggest you use the terraform repo, since you are using EKS.

Having said that, you should use `jx boot` instead of `jx install` (This command will be removed in September 1, and is only kept for legacy reasons and on-prem cluster). Also the versionstream needs to be minimum v1.0.489 (else, you will have older helm chart versions).
