### ISSUE TITLE
terraform init fails with missing region

### ISSUE THREAD

**Issue by arpad9** [jenkins-x/terraform-aws-eks-jx#99]
### Summary 
On terraform init, the following error occurs:

```
Error: Missing required argument
The argument "region" is required, but was not set.
```
The relevant trace is here:
```
2020-06-29T01:25:03.360-0500 [DEBUG] plugin: plugin started: path=/home/arpad/adaptly/jx-temp/terraform/.terraform/plugins/linux_amd64/terraform-provider-aws_v2.68.0_x4 pid=123671
2020-06-29T01:25:03.360-0500 [DEBUG] plugin: waiting for RPC address: path=/home/arpad/adaptly/jx-temp/terraform/.terraform/plugins/linux_amd64/terraform-provider-aws_v2.68.0_x4
2020/06/29 01:25:03 [WARN] <root>: eval: *terraform.EvalValidateProvider, non-fatal err: Missing required argument: The argument "region" is required, but was not set.
2020/06/29 01:25:03 [ERROR] <root>: eval: *terraform.EvalSequence, err: Missing required argument: The argument "region" is required, but was not set.
2020/06/29 01:25:03 [ERROR] <root>: eval: *terraform.EvalOpFilter, err: Missing required argument: The argument "region" is required, but was not set.
2020/06/29 01:25:03 [ERROR] <root>: eval: *terraform.EvalSequence, err: Missing required argument: The argument "region" is required, but was not set.
```

### Steps to reproduce the behavior
Create main.tf as outlined in the documentation.
Run `terraform init`

### Expected behavior

Cluster creates.

### Actual behavior

Error: Missing required argument
The argument "region" is required, but was not set.

### Terraform version

The output of `terraform version` is: 

```
Terraform v0.12.28
+ provider.aws v2.68.0
+ provider.kubernetes v1.11.1
+ provider.local v1.4.0
+ provider.null v2.1.2
+ provider.random v2.2.1
+ provider.template v2.1.2
```

### Module version

`1.1.0`

### Operating system

Ubuntu 20.04

### Solution

The solution to this was adding this stanza:

```
provider "aws" {
  region  = "us-west-2"
  profile = "prod-west"
}
```
If this is just a documentation issue, I'd be happy to do a PR.

**Comment by ankitm123** [comment]
Very weird, the default region is set to `us-east-1`. See: https://github.com/jenkins-x/terraform-aws-eks-jx/blob/master/variables.tf#L7

I think this may be an issue with loading auth creds (a possible bug with the aws-sdk?), I had to use:
```
AWS_PROFILE=test AWS_REGION=us-east-1 terraform init
```
in the past.

**Comment by arpad9** [comment]
Ohhh.  Well okay.  That's the other solution.  I usually use my profiles to mange region and don't usually have AWS_REGION (or `AWS_*` for that matter) set.

Setting AWS_REGION does handle the problem.  Maybe adding a note in the README?  I can do these three issues in a single PR.

Setting AWS_PROFILE doesn't help.

**Comment by ankitm123** [comment]
forgot to mention, I also used to set this:
`export AWS_SDK_LOAD_CONFIG=1`

**Comment by arpad9** [comment]
Closing, leaving issue #101 as a reference for a PR doc update.
